package:
  name: copy-jdk-configs-el10-aarch64
  version: 4.1

source:
  - url: https://download.rockylinux.org/vault/rocky/10.0/devel/aarch64/os/Packages/c/copy-jdk-configs-4.1-7.el10.noarch.rpm
    sha256: 6946b8e4605985330dc92e5a7088307fdb550afa38523156ecaccf7a6fecf2b7
    no_hoist: true
    folder: binary

build:
  skip: True  # [not (linux and aarch64)]
  number: {{ build_number }}
  noarch: generic

about:
  home: https://pagure.io/copy_jdk_configs
  license: BSD
  license_family: BSD
  license_file:
    - LICENSE
  summary: (CDT) JDKs configuration files copier
  description: |
    Utility script to transfer JDKs configuration files between updates or for
    archiving. With script to fix incorrectly created rpmnew files
  doc_url: https://pagure.io/copy_jdk_configs
  dev_url: https://pagure.io/copy_jdk_configs

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
